name: SqrtOne的小站
description: SqrtOne的小站

url: "https://sqrtone.github.io"
baseurl: ""
permalink: /blog/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  math_engine: mathjax