name: 晴理·SqrtOneの日记本
description: 晴理·SqrtOneの日记本

avatar: https://ql-file.netlify.app/avatar.jpg
background_image: https://ql-file.netlify.app/bg.jpg

url: "https://sqrtone.dpdns.org"
baseurl: ""
permalink: /blog/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

  math_engine: mathjax
